CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE');

CREATE TABLE MANAGERS (
managerId INTEGER AUTO_INCREMENT  PRIMARY KEY,
firstname VARCHAR(250) NOT NULL,
lastname VARCHAR(250) NOT NULL,
email VARCHAR(250) NOT NULL,
birthday VARCHAR(250) NOT NULL,
gender gender_enum DEFAULT 'MALE'
);
CREATE TABLE SELLERS (
sellerId INTEGER AUTO_INCREMENT  PRIMARY KEY,
managerId INTEGER NOT NULL,
firstname VARCHAR(250) NOT NULL,
lastname VARCHAR(250) NOT NULL,
phone VARCHAR(250) NOT NULL,
salary INTEGER NOT NULL
);
